export const {
  SALES_PORT,
  MONGO_DB_URL,
  RABBIT_MQ_URL,
  PRODUCT_TOPIC,
  PRODUCT_STOCK_UPDATE_QUEUE,
  PRODUCT_STOCK_UPDATE_ROUTING_KEY,
  SALES_CONFIRMATION_QUEUE,
  SALES_CONFIRMATION_ROUTING_KEY,
  JWT_SECRET,
  PRODUCT_API_URL
} = process.env
